export const WEEK_DAYS = ['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira'];
export const SLOT_DEFINITIONS = [
  { slot: 1, label: '1ª', time: '07:20 - 08:10' }, { slot: 2, label: '2ª', time: '08:10 - 09:00' },
  { slot: 3, label: '3ª', time: '09:30 - 10:20' }, { slot: 4, label: '4ª', time: '10:20 - 11:10' }, { slot: 5, label: '5ª', time: '11:10 - 12:00' }, { slot: 6, label: '6ª', time: '13:00 - 13:50' },
  { slot: 7, label: '7ª', time: '13:50 - 14:40' }, { slot: 8, label: '8ª', time: '15:00 - 15:50' }, { slot: 9, label: '9ª', time: '15:50 - 16:40' },
];
export const FIXED_AREAS = [{ nome: 'Exatas', base: 'comum' },{ nome: 'Natureza', base: 'comum' },{ nome: 'Humanas', base: 'comum' },{ nome: 'Linguagens', base: 'comum' },{ nome: 'Técnica', base: 'tecnica' }];
export const normalizeFixedAreas = (areas = []) => FIXED_AREAS.map((fixed) => { const existing = (Array.isArray(areas) ? areas : []).find((area) => String(area?.nome || '').trim().toLowerCase() === fixed.nome.toLowerCase()); return existing ? { ...existing, nome: fixed.nome, base: fixed.base } : { ...fixed }; });
export const FC_RULES = { 1: { '1º': { dia: 'Segunda-feira', slot: 6 }, '2º': { dia: 'Segunda-feira', slot: 7 }, '3º': { dia: 'Segunda-feira', slot: 8 } }, 2: { '1º': { dia: 'Segunda-feira', slot: 6 }, '2º': { dia: 'Segunda-feira', slot: 7 }, '3º': { dia: 'Quarta-feira', slot: 6 } } };
export const getTurmaSerie = (nome = '') => { const match = String(nome).match(/(\d+)\s*º|\b(\d+)\b/); return match ? `${match[1] || match[2]}º` : null; };
export const normalizeAgenda = (value) => Array.isArray(value) ? value.map((item) => typeof item === 'string' ? item : item?.id || item) : [];
const normalizeDay = (day) => (typeof day === 'number' || /^\d+$/.test(String(day))) ? WEEK_DAYS[Number(day) - 1] || String(day) : String(day || '');
const slotKey = (dia, slot) => `${normalizeDay(dia)}:${Number(slot)}`;
const professorById = (items, id) => items.find((item) => String(item.id) === String(id));
const maxConsecutives = (professor, vinculo) => Number(vinculo?.max_aulas_consecutivas || professor?.max_aulas_consecutivas_default || 2);
const daySlots = (schedule, day) => Object.values(schedule || {}).filter((item) => normalizeDay(item?.dia) === normalizeDay(day)).map((item) => Number(item.slot));
const consecutiveIfPlaced = (schedule, day, slot) => { const values = [...new Set([...daySlots(schedule, day), Number(slot)])].sort((a,b)=>a-b); let longest=0,run=0,previous=null; values.forEach((value)=>{run=previous!==null&&value===previous+1?run+1:1;longest=Math.max(longest,run);previous=value;}); return longest; };
const adjacentCount = (schedule, day, slot) => daySlots(schedule, day).filter((value) => value === Number(slot)-1 || value === Number(slot)+1).length;
const mergeProfessores = (configuracao, professores) => { const merged = [...(Array.isArray(professores)?professores:[]), ...(Array.isArray(configuracao?.professores)?configuracao.professores:[]), ...(Array.isArray(configuracao?.professorManual)?configuracao.professorManual:[])]; return Array.from(new Map(merged.filter(Boolean).map((item)=>[String(item.id),item])).values(); };

export const generateHorario = ({ configuracao = {}, turmas = [], professores = [], vinculos = [], pdtMap = {}, areas = [], disciplinas = [], folgas = [], indisponibilidades = [], formacoesArea = [], fcRules = [] }) => {
  const effectiveAreas = normalizeFixedAreas(configuracao?.areas?.length ? configuracao.areas : areas);
  const effectiveDisciplinas = configuracao?.disciplinas?.length ? configuracao.disciplinas : disciplinas;
  const effectiveProfessores = mergeProfessores(configuracao, professores);
  const effectiveTurmas = configuracao?.turmas?.length ? turmas.filter((turma) => configuracao.turmas.map(String).includes(String(turma.id))) : turmas;
  const professorMap = Object.fromEntries(effectiveProfessores.map((item)=>[String(item.id),item])); const disciplinaMap = Object.fromEntries(effectiveDisciplinas.map((item)=>[String(item.id),item])); const areaMap = Object.fromEntries(effectiveAreas.map((item)=>[String(item.id),item])); const turmaMap = Object.fromEntries(effectiveTurmas.map((item)=>[String(item.id),item])); const selectedTurmaIds = new Set(effectiveTurmas.map((turma)=>String(turma.id)));
  const validation=[]; const generated=[]; const turmaSchedule={}; const professorSchedule={};
  const folgaMap={}; folgas.forEach(({professor_id,dia_semana})=>{if(professor_id)(folgaMap[String(professor_id)]||=[]).push(normalizeDay(dia_semana));});
  const indisponibilidadeMap={}; indisponibilidades.forEach(({professor_id,dia_semana,aula_numero})=>{if(professor_id)(indisponibilidadeMap[String(professor_id)]||=[]).push(slotKey(dia_semana,aula_numero));});
  const formacaoMap={}; formacoesArea.forEach(({area_id,dia_semana,aula_numero})=>{if(area_id)(formacaoMap[String(area_id)]||=[]).push(slotKey(dia_semana,aula_numero));});
  const rules = fcRules && !Array.isArray(fcRules) && Object.keys(fcRules).length ? fcRules : FC_RULES[Number(configuracao.semestre)||1];
  effectiveTurmas.forEach((turma)=>{ const rule=rules?.[getTurmaSerie(turma.nome||turma.turma_nome||'')]; const professorId=pdtMap[String(turma.id)]||pdtMap[turma.id]; if(!rule||!professorId){validation.push({turma:turma.nome||'Turma',mensagem:!professorId?'Turma sem PDT para a aula obrigatória de FC.':'Não foi possível identificar a regra de FC da turma.'});return;} const professor=professorById(effectiveProfessores,professorId); if(!professor){validation.push({turma:turma.nome||'Turma',mensagem:'O PDT informado não pertence à configuração atual.'});return;} const key=slotKey(rule.dia,rule.slot); if((folgaMap[String(professorId)]||[]).includes(rule.dia)||(indisponibilidadeMap[String(professorId)]||[]).includes(key)){validation.push({turma:turma.nome||'Turma',professor:professor.nome,mensagem:'A FC obrigatória conflita com a disponibilidade do PDT.'});return;} if((formacaoMap[String(professor.area_id)]||[]).includes(key)){validation.push({turma:turma.nome||'Turma',professor:professor.nome,mensagem:'A FC obrigatória conflita com a formação da área do PDT.'});return;} turmaSchedule[String(turma.id)]||={}; professorSchedule[String(professorId)]||={}; if(turmaSchedule[String(turma.id)][key]||professorSchedule[String(professorId)][key]){validation.push({turma:turma.nome||'Turma',professor:professor.nome,mensagem:'Conflito ao reservar a FC obrigatória.'});return;} const item={turma_id:String(turma.id),turma_nome:turma.nome||'Turma',professor_id:String(professorId),professor_nome:professor.nome||'PDT',disciplina:'Formação para a Cidadania',disciplina_id:null,dia:rule.dia,slot:rule.slot,tipo:'FC'}; turmaSchedule[String(turma.id)][key]=item; professorSchedule[String(professorId)][key]=item; generated.push(item); });
  const tasks=vinculos.map((vinculo)=>{const professor=professorMap[String(vinculo.professor_id)];const turma=turmaMap[String(vinculo.turma_id)];const disciplina=disciplinaMap[String(vinculo.disciplina_id)];const aulas=Number(vinculo.aulas_semana??vinculo.aulas_semanais??0);if(!selectedTurmaIds.has(String(vinculo.turma_id))||!professor||!turma||!disciplina||aulas<=0)return null;const area=areaMap[String(disciplina.area_id)];if(!area){validation.push({professor:professor.nome,turma:turma.nome,disciplina:disciplina.nome,mensagem:`A disciplina "${disciplina.nome}" não possui uma área válida nesta configuração.`});return null;}return {...vinculo,professor,turma,disciplina,area,aulas,maxConsecutivo:maxConsecutives(professor,vinculo)};}).filter(Boolean).sort((a,b)=>(String(b.area.base)==='tecnica')-(String(a.area.base)==='tecnica')||b.aulas-a.aulas);
  tasks.forEach((task,order)=>{let remaining=task.aulas;const professorId=String(task.professor_id),turmaId=String(task.turma_id);while(remaining>0){const candidates=[];WEEK_DAYS.forEach((day)=>SLOT_DEFINITIONS.forEach(({slot})=>{const key=slotKey(day,slot);if((folgaMap[professorId]||[]).includes(day)||(indisponibilidadeMap[professorId]||[]).includes(key)||(formacaoMap[String(task.disciplina.area_id)]||[]).includes(key)||professorSchedule[professorId]?.[key]||turmaSchedule[turmaId]?.[key])return;const consecutive=consecutiveIfPlaced(professorSchedule[professorId]||{},day,slot);if(consecutive>task.maxConsecutivo)return;const adjacent=adjacentCount(professorSchedule[professorId]||{},day,slot),turmaLoad=daySlots(turmaSchedule[turmaId],day).length,professorLoad=daySlots(professorSchedule[professorId],day).length;candidates.push({day,slot,score:adjacent*20-turmaLoad*2-professorLoad+(remaining===1?1:0)});}));candidates.sort((a,b)=>b.score-a.score||a.slot-b.slot||WEEK_DAYS.indexOf(a.day)-WEEK_DAYS.indexOf(b.day));const candidate=candidates[0];if(!candidate){validation.push({professor:task.professor.nome,turma:task.turma.nome,disciplina:task.disciplina.nome,mensagem:`Não foi possível distribuir todas as ${task.aulas} aulas dentro das restrições.`});break;}const key=slotKey(candidate.day,candidate.slot);const record={turma_id:turmaId,turma_nome:task.turma.nome||'Turma',professor_id:professorId,professor_nome:task.professor.nome||'Professor',disciplina_id:task.disciplina.id,disciplina:task.disciplina.nome||'Disciplina',dia:candidate.day,slot:candidate.slot,tipo:'Regular',ordem:order};turmaSchedule[turmaId]||={};professorSchedule[professorId]||={};turmaSchedule[turmaId][key]=record;professorSchedule[professorId][key]=record;generated.push(record);remaining-=1;}});
  const grid=generated.reduce((acc,item)=>{(acc[String(item.turma_id)]||=[]).push(item);return acc;},{}); return {grid,schedule:generated,validation,fcMap:{},areas:effectiveAreas,disciplinas:effectiveDisciplinas};
};
export const exportarGradePdf = (grade, nomeEscola='EEEP Irmã Ana Zélia da Fonseca') => { const { jsPDF } = window.jspdf || {}; if (!jsPDF) return; const doc=new jsPDF(); doc.setFontSize(16); doc.text(nomeEscola,14,16); doc.setFontSize(11); doc.text('Grade escolar gerada',14,24); let y=34; Object.entries(grade||{}).forEach(([turmaId,aulas])=>{if(y>260){doc.addPage();y=20;}doc.text(`Turma ${turmaId}`,14,y);y+=8;aulas.forEach((aula)=>{doc.text(`${aula.dia} - ${aula.slot}ª - ${aula.disciplina} (${aula.professor_nome})`,18,y);y+=7;});y+=5;});doc.save('grade_horario.pdf');};