import { Link } from "react-router-dom";
import { FaArrowRight, FaBell, FaCalendarAlt, FaCheckCircle, FaClipboardList, FaGraduationCap, FaShieldAlt, FaUsers } from "react-icons/fa";
import logo from "../assets/images/logo.png";

const features = [
  { icon: FaUsers, title: "Gestão de alunos", description: "Centralize turmas, alunos, responsáveis e informações essenciais da escola." },
  { icon: FaClipboardList, title: "Ocorrências", description: "Registre, acompanhe e organize ocorrências escolares em poucos passos." },
  { icon: FaCalendarAlt, title: "Horários inteligentes", description: "Monte grades respeitando professores, turmas, áreas, cargas e disponibilidades." },
  { icon: FaBell, title: "Notificações", description: "Mantenha a equipe informada sobre acontecimentos importantes da rotina escolar." },
];
const workflow = ["A gestão organiza a rotina em um só lugar.", "Professores registram e acompanham o que acontece.", "Alunos e responsáveis ganham acesso a informações úteis."];

export const Landing = () => (
  <main className="min-h-screen overflow-x-hidden bg-white text-slate-900 dark:bg-slate-950 dark:text-white">
    <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/85">
      <div className="mx-auto flex h-16 w-full max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
        <a href="#inicio" className="flex min-w-0 items-center gap-2.5"><img src={logo} alt="Log Zélia" width="40" height="40" className="h-9 w-9 shrink-0 rounded-xl object-contain sm:h-10 sm:w-10" /><span className="truncate font-montserrat text-base font-extrabold tracking-tight sm:text-lg">LOG <span className="text-orange-500">ZÉLIA</span></span></a>
        <nav className="hidden items-center gap-6 text-sm font-semibold text-slate-600 md:flex dark:text-slate-300"><a href="#recursos" className="transition hover:text-green-700">Recursos</a><a href="#como-funciona" className="transition hover:text-green-700">Como funciona</a><a href="#seguranca" className="transition hover:text-green-700">Segurança</a></nav>
        <div className="flex items-center gap-2"><Link to="/consultar-ocorrencias" className="hidden rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-100 sm:inline-flex dark:text-slate-300">Consultar ocorrência</Link><Link to="/login" className="inline-flex items-center gap-2 rounded-xl bg-green-700 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-green-800">Entrar <FaArrowRight className="text-xs" /></Link></div>
      </div>
    </header>
    <section id="inicio" className="relative isolate overflow-hidden">
      <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_10%,rgba(22,163,74,0.13),transparent_32%),radial-gradient(circle_at_85%_20%,rgba(249,115,22,0.10),transparent_30%)]" />
      <div className="mx-auto grid min-h-[calc(100vh-4rem)] w-full max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24">
        <div className="max-w-2xl">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-green-200 bg-green-50 px-3 py-1.5 text-xs font-bold text-green-800 dark:border-green-900/50 dark:bg-green-950/40 dark:text-green-300"><FaGraduationCap /> Gestão escolar mais simples, conectada e humana</div>
          <h1 className="max-w-3xl text-4xl font-black leading-[1.04] tracking-tight sm:text-5xl lg:text-6xl">A escola organizada começa com<span className="block bg-gradient-to-r from-green-700 via-green-600 to-emerald-500 bg-clip-text text-transparent">LogZélia.</span></h1>
          <p className="mt-6 max-w-xl text-base leading-7 text-slate-600 sm:text-lg dark:text-slate-300">Uma plataforma para transformar a rotina escolar em um fluxo claro: alunos, ocorrências, professores, horários e comunicação em um só lugar.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/login" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-green-700 px-5 py-3.5 text-sm font-bold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-green-800">Acessar o sistema <FaArrowRight className="text-xs" /></Link><Link to="/consultar-ocorrencias" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-300 bg-white px-5 py-3.5 text-sm font-bold text-slate-700 transition hover:-translate-y-0.5 hover:border-green-300 hover:text-green-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Consultar ocorrência</Link></div>
          <div className="mt-8 grid grid-cols-1 gap-3 text-sm text-slate-600 sm:grid-cols-3 dark:text-slate-300">{["Pensado para escolas", "Responsivo no celular", "Experiência simples"].map((item) => <div key={item} className="flex items-center gap-2"><FaCheckCircle className="shrink-0 text-green-600" /><span>{item}</span></div>)}</div>
        </div>
        <div className="relative mx-auto w-full max-w-xl lg:max-w-none"><div className="absolute -inset-6 rounded-[2rem] bg-green-500/10 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-white p-3 shadow-2xl dark:border-slate-800 dark:bg-slate-900"><div className="rounded-[1.5rem] bg-slate-950 p-4 text-white sm:p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[0.22em] text-slate-400">Visão geral</p><h2 className="mt-1 text-lg font-bold sm:text-xl">Painel escolar</h2></div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-green-500/15 text-green-400"><FaGraduationCap /></div></div><div className="grid grid-cols-3 gap-2.5">{[["Alunos","518"],["Ocorrências","40"],["Turmas","12"]].map(([label,value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><p className="text-[10px] uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>)}</div><div className="mt-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-slate-300">Fluxo de ocorrências</span><span className="rounded-full bg-green-500/15 px-2 py-1 font-semibold text-green-300">Últimos 7 dias</span></div><div className="mt-5 flex h-32 items-end gap-2">{[24,42,30,62,46,78,54,68,40,58,74,48].map((height,index)=><div key={index} className="flex-1 rounded-t-lg bg-gradient-to-t from-green-700 to-emerald-300/80" style={{height:`${height}%`}} />)}</div></div></div></div></div>
      </div>
    </section>
    <section id="recursos" className="border-t border-slate-100 bg-slate-50/70 py-20 dark:border-slate-900 dark:bg-slate-900/40 sm:py-24"><div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-green-700 dark:text-green-400">Recursos</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Menos planilha. Mais clareza.</h2><p className="mt-4 text-base leading-7 text-slate-600 dark:text-slate-300">Tudo que a equipe precisa para cuidar da rotina escolar sem transformar cada tarefa em uma novela de planilhas.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({icon:Icon,title,description})=><article key={title} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl dark:border-slate-800 dark:bg-slate-950"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-green-50 text-green-700 dark:bg-green-950/40 dark:text-green-300"><Icon /></div><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{description}</p></article>)}</div></div></section>
    <section id="como-funciona" className="py-20 sm:py-24"><div className="mx-auto grid w-full max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-green-700 dark:text-green-400">Como funciona</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Uma experiência feita para o ritmo real da escola.</h2><p className="mt-4 text-base leading-7 text-slate-600 dark:text-slate-300">Da gestão ao professor, cada perfil encontra o que precisa sem um labirinto de menus.</p></div><div className="space-y-3">{workflow.map((item,index)=><div key={item} className="flex gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-green-700 text-sm font-black text-white">0{index+1}</div><div><p className="font-semibold leading-6 text-slate-800 dark:text-slate-100">{item}</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Fluxos objetivos e informações no lugar certo.</p></div></div>)}</div></div></section>
    <section id="seguranca" className="border-t border-slate-100 bg-slate-950 py-20 text-white sm:py-24"><div className="mx-auto grid w-full max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-green-400">Segurança</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Acesso certo para cada pessoa.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-slate-300">O LogZélia separa experiências públicas e áreas autenticadas, permitindo divulgar informações úteis sem abrir o painel administrativo.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Perfis com permissões","Consultas públicas controladas","Experiência responsiva","Estrutura preparada para SEO"].map(item=><div key={item} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4 text-sm font-semibold text-slate-200"><FaCheckCircle className="mb-2 text-green-400" />{item}</div>)}</div></div></section>
    <section className="border-t border-slate-200 py-16 dark:border-slate-800"><div className="mx-auto flex w-full max-w-5xl flex-col items-center justify-between gap-6 px-4 text-center sm:px-6 lg:flex-row lg:text-left"><div><h2 className="text-2xl font-black sm:text-3xl">Pronto para entrar no LogZélia?</h2><p className="mt-2 text-slate-600 dark:text-slate-400">Acesse seu ambiente ou consulte uma ocorrência escolar.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Link to="/consultar-ocorrencias" className="rounded-2xl border border-slate-300 px-5 py-3 text-sm font-bold text-slate-700 transition hover:border-green-300 hover:text-green-700 dark:border-slate-700 dark:text-slate-200">Consultar ocorrência</Link><Link to="/login" className="rounded-2xl bg-green-700 px-5 py-3 text-sm font-bold text-white transition hover:bg-green-800">Entrar no sistema</Link></div></div></section>
    <footer className="border-t border-slate-200 bg-slate-50 py-8 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto flex w-full max-w-7xl flex-col gap-3 px-4 text-sm text-slate-500 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8 dark:text-slate-400"><span>© {new Date().getFullYear()} LogZélia. Gestão escolar com propósito.</span><div className="flex gap-4"><Link to="/consultar-ocorrencias" className="hover:text-green-700">Consultar ocorrência</Link><Link to="/login" className="hover:text-green-700">Entrar</Link></div></div></footer>
  </main>
);