from pathlib import Path


def replace_once(path, old, new):
    text = path.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'Pattern not found in {path}: {old[:120]}')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')


horarios = Path('src/pages/Horarios.jsx')
custom = Path('src/components/ui/CustomSelect.jsx')
modal = Path('src/components/ui/Modal.jsx')

replace_once(
    horarios,
    """  const professorUsers = useMemo(\n    () => usuarios\n      .filter((usuario) => Number(usuario.role_id) === PROFESSOR_ROLE_ID)\n      .filter((usuario) => !currentConfig.professores.some((professor) => String(professor.usuario_id) === String(usuario.id)))\n      .map((usuario) => ({ value: String(usuario.id), label: `${usuario.nome}${usuario.pdt ? ' · PDT' : ''}` })),\n    [usuarios, currentConfig.professores],\n  );\n\n  const professorAssignmentGroups = useMemo(() => {\n""",
    """  const professorUsers = useMemo(\n    () => usuarios\n      .filter((usuario) => Number(usuario.role_id) === PROFESSOR_ROLE_ID)\n      .filter((usuario) => !currentConfig.professores.some((professor) => String(professor.usuario_id) === String(usuario.id)))\n      .map((usuario) => ({ value: String(usuario.id), label: `${usuario.nome}${usuario.pdt ? ' · PDT' : ''}` })),\n    [usuarios, currentConfig.professores],\n  );\n\n  const availablePdtTurmaOptions = useMemo(() => {\n    const assigned = new Set(\n      Object.entries(currentConfig.pdt || {})\n        .filter(([, professorId]) => String(professorId) !== String(editingProfessorId || ''))\n        .map(([turmaId]) => String(turmaId)),\n    );\n    return turmaOptions.filter(\n      (option) => currentConfig.turmas.includes(String(option.value)) &&\n        (!assigned.has(String(option.value)) || String(option.value) === String(professorDraft.pdt_turma_id)),\n    );\n  }, [currentConfig.pdt, currentConfig.turmas, editingProfessorId, professorDraft.pdt_turma_id, turmaOptions]);\n\n  const professorAssignmentGroups = useMemo(() => {\n""",
)

replace_once(
    horarios,
    """  const newAssignmentItem = () => ({\n    id: newId('assignment-item'),\n    turma_id: '',\n    disciplina_id: '',\n    aulas_semana: 2,\n    max_aulas_consecutivas: 2,\n  });\n\n  const openLinkModal = (assignment = null) => {\n    setEditingLinkProfessorId(assignment?.professor_id || null);\n    setLinkDraft({\n      professor_id: assignment?.professor_id || '',\n      items: assignment?.items?.length\n        ? assignment.items.map((item) => ({\n            id: item.id || newId('assignment-item'),\n            turma_id: String(item.turma_id || ''),\n            disciplina_id: String(item.disciplina_id || ''),\n            aulas_semana: Number(item.aulas_semana || 2),\n            max_aulas_consecutivas: Number(item.max_aulas_consecutivas || 2),\n          }))\n        : [newAssignmentItem()],\n    });\n    setVinculoModalOpen(true);\n  };\n\n  const closeLinkModal = () => {\n    setVinculoModalOpen(false);\n    setEditingLinkProfessorId(null);\n    setLinkDraft({ professor_id: '', items: [newAssignmentItem()] });\n  };\n\n  const updateAssignmentItem = (itemId, field, value) => {\n    setLinkDraft((prev) => ({\n      ...prev,\n      items: prev.items.map((item) => String(item.id) === String(itemId) ? { ...item, [field]: value } : item),\n    }));\n  };\n\n  const addAssignmentItem = () => {\n    setLinkDraft((prev) => ({ ...prev, items: [...prev.items, newAssignmentItem()] }));\n  };\n\n  const removeAssignmentItem = (itemId) => {\n    setLinkDraft((prev) => ({\n      ...prev,\n      items: prev.items.length > 1 ? prev.items.filter((item) => String(item.id) !== String(itemId)) : prev.items,\n    }));\n  };\n\n  const saveLinkFromModal = () => {\n""",
    """  const newAssignmentItem = () => ({\n    id: newId('assignment-item'),\n    turma_ids: [],\n    disciplina_id: '',\n    aulas_semana: 2,\n    max_aulas_consecutivas: 2,\n  });\n\n  const openLinkModal = (assignment = null) => {\n    setEditingLinkProfessorId(assignment?.professor_id || null);\n\n    const groupedItems = [];\n    const groupedMap = new Map();\n    (assignment?.items || []).forEach((item) => {\n      const key = `${String(item.disciplina_id || '')}|${Number(item.aulas_semana || 2)}|${Number(item.max_aulas_consecutivas || 2)}`;\n      if (!groupedMap.has(key)) {\n        const grouped = {\n          id: item.id || newId('assignment-item'),\n          turma_ids: [],\n          disciplina_id: String(item.disciplina_id || ''),\n          aulas_semana: Number(item.aulas_semana || 2),\n          max_aulas_consecutivas: Number(item.max_aulas_consecutivas || 2),\n        };\n        groupedMap.set(key, grouped);\n        groupedItems.push(grouped);\n      }\n      const target = groupedMap.get(key);\n      if (item.turma_id && !target.turma_ids.includes(String(item.turma_id))) target.turma_ids.push(String(item.turma_id));\n    });\n\n    setLinkDraft({\n      professor_id: assignment?.professor_id || '',\n      items: groupedItems.length ? groupedItems : [newAssignmentItem()],\n    });\n    setVinculoModalOpen(true);\n  };\n\n  const closeLinkModal = () => {\n    setVinculoModalOpen(false);\n    setEditingLinkProfessorId(null);\n    setLinkDraft({ professor_id: '', items: [newAssignmentItem()] });\n  };\n\n  const updateAssignmentItem = (itemId, field, value) => {\n    setLinkDraft((prev) => ({\n      ...prev,\n      items: prev.items.map((item) => String(item.id) === String(itemId) ? { ...item, [field]: value } : item),\n    }));\n  };\n\n  const addAssignmentItem = () => {\n    setLinkDraft((prev) => ({ ...prev, items: [...prev.items, newAssignmentItem()] }));\n  };\n\n  const removeAssignmentItem = (itemId) => {\n    setLinkDraft((prev) => ({\n      ...prev,\n      items: prev.items.length > 1 ? prev.items.filter((item) => String(item.id) !== String(itemId)) : prev.items,\n    }));\n  };\n\n  const saveLinkFromModal = () => {\n""",
)

replace_once(
    horarios,
    """    const seenTurmas = new Set();\n    const items = linkDraft.items.map((item) => ({\n      ...item,\n      turma_id: String(item.turma_id || ''),\n      disciplina_id: String(item.disciplina_id || ''),\n      aulas_semana: Number(item.aulas_semana),\n      max_aulas_consecutivas: Number(item.max_aulas_consecutivas),\n    }));\n\n    for (const item of items) {\n      if (!currentConfig.turmas.map(String).includes(item.turma_id) || !byId(currentConfig.disciplinas, item.disciplina_id) || !Number.isFinite(item.aulas_semana) || item.aulas_semana <= 0 || !Number.isFinite(item.max_aulas_consecutivas) || item.max_aulas_consecutivas <= 0) {\n        return notify.error('Cada linha precisa de turma, matéria, aulas por semana e máximo de consecutivas válidos.');\n      }\n      if (seenTurmas.has(item.turma_id)) return notify.error('Cada turma pode aparecer apenas uma vez na mesma atribuição.');\n      seenTurmas.add(item.turma_id);\n    }\n\n    const professorId = String(linkDraft.professor_id);\n    setCurrentConfig((prev) => ({\n      ...prev,\n      professorTurmas: [\n        ...prev.professorTurmas.filter((item) => String(item.professor_id) !== professorId),\n        ...items.map((item) => ({\n          id: newId('link'),\n          professor_id: professorId,\n          turma_id: item.turma_id,\n          disciplina_id: item.disciplina_id,\n          aulas_semana: item.aulas_semana,\n          max_aulas_consecutivas: item.max_aulas_consecutivas,\n        })),\n      ],\n    }));\n""",
    """    const seenTurmas = new Set();\n    const items = linkDraft.items.map((item) => ({\n      ...item,\n      turma_ids: Array.from(new Set((Array.isArray(item.turma_ids) ? item.turma_ids : []).map(String))),\n      disciplina_id: String(item.disciplina_id || ''),\n      aulas_semana: Number(item.aulas_semana),\n      max_aulas_consecutivas: Number(item.max_aulas_consecutivas),\n    }));\n\n    for (const item of items) {\n      if (!item.turma_ids.length || !byId(currentConfig.disciplinas, item.disciplina_id) || !Number.isFinite(item.aulas_semana) || item.aulas_semana <= 0 || !Number.isFinite(item.max_aulas_consecutivas) || item.max_aulas_consecutivas <= 0) {\n        return notify.error('Cada grupo precisa de uma ou mais turmas, matéria, aulas por semana e máximo de consecutivas válidos.');\n      }\n      for (const turmaId of item.turma_ids) {\n        if (!currentConfig.turmas.map(String).includes(turmaId)) return notify.error('Existe uma turma selecionada que não pertence à configuração.');\n        if (seenTurmas.has(turmaId)) return notify.error('A mesma turma não pode aparecer em dois grupos da mesma atribuição.');\n        seenTurmas.add(turmaId);\n      }\n    }\n\n    const professorId = String(linkDraft.professor_id);\n    setCurrentConfig((prev) => ({\n      ...prev,\n      professorTurmas: [\n        ...prev.professorTurmas.filter((item) => String(item.professor_id) !== professorId),\n        ...items.flatMap((item) => item.turma_ids.map((turmaId) => ({\n          id: newId('link'),\n          professor_id: professorId,\n          turma_id: turmaId,\n          disciplina_id: item.disciplina_id,\n          aulas_semana: item.aulas_semana,\n          max_aulas_consecutivas: item.max_aulas_consecutivas,\n        }))),\n      ],\n    }));\n""",
)

replace_once(
    horarios,
    """<CustomSelect label=\"Professor da base\" value={professorDraft.usuario_id} onChange={(value) => setProfessorDraft((prev) => ({ ...prev, usuario_id: value, pdt_turma_id: '' }))} options={usuarios.filter((usuario) => Number(usuario.role_id) === PROFESSOR_ROLE_ID).map((usuario) => ({ value: String(usuario.id), label: `${usuario.nome}${usuario.pdt ? ' · PDT' : ''}` }))} placeholder=\"Selecione o professor\" showSearch emptyLabel=\"Nenhum professor disponível\" disabled={Boolean(editingProfessorId)} />""",
    """<CustomSelect label=\"Professor da base\" value={professorDraft.usuario_id} onChange={(value) => setProfessorDraft((prev) => ({ ...prev, usuario_id: value, pdt_turma_id: '' }))} options={editingProfessorId && selectedModalProfessor?.usuario_id ? [{ value: String(selectedModalProfessor.usuario_id), label: `${selectedModalProfessor.nome}${selectedModalUser?.pdt ? ' · PDT' : ''}` }, ...professorUsers] : professorUsers} placeholder=\"Selecione o professor\" showSearch emptyLabel=\"Nenhum professor disponível\" disabled={Boolean(editingProfessorId)} />""",
)

replace_once(
    horarios,
    """<CustomSelect label=\"Turma correspondente ao PDT\" value={professorDraft.pdt_turma_id} onChange={(value) => setProfessorDraft((prev) => ({ ...prev, pdt_turma_id: value }))} options={turmaOptions.filter((option) => currentConfig.turmas.includes(String(option.value)))} placeholder=\"Selecione a turma\" emptyLabel=\"Selecione turmas na Etapa 2\" />""",
    """<CustomSelect label=\"Turma correspondente ao PDT\" value={professorDraft.pdt_turma_id} onChange={(value) => setProfessorDraft((prev) => ({ ...prev, pdt_turma_id: value }))} options={availablePdtTurmaOptions} placeholder=\"Selecione a turma\" emptyLabel=\"Todas as turmas selecionadas já possuem PDT\" />""",
)

old_assignment_modal = """          <div className=\"space-y-3\"><div className=\"flex items-center justify-between gap-3\"><div><h4 className=\"font-semibold text-slate-900 dark:text-white\">Turmas e matérias</h4><p className=\"text-xs text-slate-500 dark:text-slate-400\">Uma matéria diferente pode ser escolhida para cada turma da mesma atribuição.</p></div><Button type=\"button\" variant=\"secondary\" onClick={addAssignmentItem}><FaPlus className=\"mr-2\" /> Adicionar turma</Button></div>\n            {linkDraft.items.map((item, index) => <div key={item.id} className=\"rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900\"><div className=\"mb-3 flex items-center justify-between gap-3\"><span className=\"text-xs font-bold uppercase tracking-wide text-slate-500\">Turma {index + 1}</span>{linkDraft.items.length > 1 && <button type=\"button\" onClick={() => removeAssignmentItem(item.id)} className=\"rounded-lg p-2 text-red-600 transition hover:bg-red-50 dark:hover:bg-red-950\"><FaTrash /></button>}</div><div className=\"grid gap-4 sm:grid-cols-2\"><CustomSelect label=\"Turma\" value={item.turma_id} onChange={(value) => updateAssignmentItem(item.id, 'turma_id', value)} options={turmaOptions.filter((option) => currentConfig.turmas.includes(String(option.value)))} placeholder=\"Selecione a turma\" emptyLabel=\"Selecione turmas na Etapa 2\" /><CustomSelect label=\"Matéria\" value={item.disciplina_id} onChange={(value) => updateAssignmentItem(item.id, 'disciplina_id', value)} options={disciplinaOptions} placeholder=\"Selecione a matéria\" emptyLabel=\"Cadastre disciplinas na Etapa 3\" /><FormInput label=\"Aulas por semana\" type=\"number\" min=\"1\" value={item.aulas_semana} onChange={(event) => updateAssignmentItem(item.id, 'aulas_semana', Number(event.target.value) || 0)} /><FormInput label=\"Máx. de aulas consecutivas\" type=\"number\" min=\"1\" value={item.max_aulas_consecutivas} onChange={(event) => updateAssignmentItem(item.id, 'max_aulas_consecutivas', Number(event.target.value) || 0)} /></div></div>)}\n          </div>"""
new_assignment_modal = """          <div className=\"space-y-3\"><div className=\"flex items-center justify-between gap-3\"><div><h4 className=\"font-semibold text-slate-900 dark:text-white\">Turmas, matéria e carga</h4><p className=\"text-xs text-slate-500 dark:text-slate-400\">Selecione várias turmas no mesmo grupo quando o professor lecionar a mesma matéria e carga para todas.</p></div><Button type=\"button\" variant=\"secondary\" onClick={addAssignmentItem}><FaPlus className=\"mr-2\" /> Adicionar grupo</Button></div>\n            {linkDraft.items.map((item, index) => <div key={item.id} className=\"rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900\"><div className=\"mb-3 flex items-center justify-between gap-3\"><span className=\"text-xs font-bold uppercase tracking-wide text-slate-500\">Grupo {index + 1}</span>{linkDraft.items.length > 1 && <button type=\"button\" onClick={() => removeAssignmentItem(item.id)} className=\"rounded-lg p-2 text-red-600 transition hover:bg-red-50 dark:hover:bg-red-950\"><FaTrash /></button>}</div><div className=\"grid gap-4 sm:grid-cols-2\"><CustomSelect label=\"Turmas\" value={item.turma_ids} multiple onChange={(value) => updateAssignmentItem(item.id, 'turma_ids', value)} options={turmaOptions.filter((option) => currentConfig.turmas.includes(String(option.value)))} placeholder=\"Selecione uma ou mais turmas\" emptyLabel=\"Selecione turmas na Etapa 2\" showSearch /><CustomSelect label=\"Matéria\" value={item.disciplina_id} onChange={(value) => updateAssignmentItem(item.id, 'disciplina_id', value)} options={disciplinaOptions} placeholder=\"Selecione a matéria\" emptyLabel=\"Cadastre disciplinas na Etapa 3\" /><FormInput label=\"Aulas por semana\" type=\"number\" min=\"1\" value={item.aulas_semana} onChange={(event) => updateAssignmentItem(item.id, 'aulas_semana', Number(event.target.value) || 0)} /><FormInput label=\"Máx. de aulas consecutivas\" type=\"number\" min=\"1\" value={item.max_aulas_consecutivas} onChange={(event) => updateAssignmentItem(item.id, 'max_aulas_consecutivas', Number(event.target.value) || 0)} /></div></div>)}\n          </div>"
replace_once(horarios, old_assignment_modal, new_assignment_modal)

# Improve grouped assignment summary so each group clearly shows all selected turmas after editing.
replace_once(
    horarios,
    """<div className=\"mt-4 space-y-2\">{assignment.items.map((item) => <div key={item.id} className=\"grid gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-center dark:border-slate-800 dark:bg-slate-900\"><div><span className=\"text-[10px] font-bold uppercase tracking-wide text-slate-400\">Turma</span><p className=\"text-sm font-semibold text-slate-800 dark:text-slate-200\">{byId(turmas, item.turma_id)?.nome || 'Turma'}</p></div><div><span className=\"text-[10px] font-bold uppercase tracking-wide text-slate-400\">Matéria</span><p className=\"text-sm font-semibold text-slate-800 dark:text-slate-200\">{byId(currentConfig.disciplinas, item.disciplina_id)?.nome || 'Disciplina'}</p></div><div className=\"rounded-lg bg-white px-3 py-2 text-center dark:bg-slate-950\"><div className=\"text-sm font-bold text-slate-900 dark:text-white\">{item.aulas_semana}</div><div className=\"text-[10px] uppercase tracking-wide text-slate-400\">aulas/sem.</div></div><div className=\"rounded-lg bg-white px-3 py-2 text-center dark:bg-slate-950\"><div className=\"text-sm font-bold text-slate-900 dark:text-white\">{item.max_aulas_consecutivas}</div><div className=\"text-[10px] uppercase tracking-wide text-slate-400\">máx.</div></div></div>)}</div>""",
    """<div className=\"mt-4 space-y-2\">{assignment.items.map((item) => <div key={item.id} className=\"grid gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 sm:grid-cols-[1.3fr_1fr_auto_auto] sm:items-center dark:border-slate-800 dark:bg-slate-900\"><div><span className=\"text-[10px] font-bold uppercase tracking-wide text-slate-400\">Turma</span><p className=\"text-sm font-semibold text-slate-800 dark:text-slate-200\">{byId(turmas, item.turma_id)?.nome || 'Turma'}</p></div><div><span className=\"text-[10px] font-bold uppercase tracking-wide text-slate-400\">Matéria</span><p className=\"text-sm font-semibold text-slate-800 dark:text-slate-200\">{byId(currentConfig.disciplinas, item.disciplina_id)?.nome || 'Disciplina'}</p></div><div className=\"rounded-lg bg-white px-3 py-2 text-center dark:bg-slate-950\"><div className=\"text-sm font-bold text-slate-900 dark:text-white\">{item.aulas_semana}</div><div className=\"text-[10px] uppercase tracking-wide text-slate-400\">aulas/sem.</div></div><div className=\"rounded-lg bg-white px-3 py-2 text-center dark:bg-slate-950\"><div className=\"text-sm font-bold text-slate-900 dark:text-white\">{item.max_aulas_consecutivas}</div><div className=\"text-[10px] uppercase tracking-wide text-slate-400\">máx.</div></div></div>)}</div>""",
)

# Modal width becomes content-aware; CustomSelect controls the intrinsic minimum width.
replace_once(
    modal,
    "className={`\n          relative z-9999\n          bg-white dark:bg-slate-950 rounded-2xl shadow-xl max-w-2xl w-full max-h-[92vh]",
    "className={`\n          relative z-9999\n          bg-white dark:bg-slate-950 rounded-2xl shadow-xl w-fit min-w-[min(92vw,32rem)] max-w-[calc(100vw-2rem)] max-h-[92vh]",
)

# CustomSelect: make the dropdown/modal width respond to the widest option and use generic multi-select copy.
replace_once(
    custom,
    "  const [searchTerm, setSearchTerm] = useState(\"\");\n  const rootRef = useRef(null);\n",
    "  const [searchTerm, setSearchTerm] = useState(\"\");\n  const [menuMinWidth, setMenuMinWidth] = useState(240);\n  const rootRef = useRef(null);\n\n  useEffect(() => {\n    const labels = [placeholder, ...options.map((option) => option.label)];\n    const maxLength = Math.max(0, ...labels.map((label) => String(label || '').length));\n    const nextWidth = Math.min(Math.max(240, Math.round(maxLength * 7.2 + 72)), 720);\n    setMenuMinWidth(nextWidth);\n  }, [options, placeholder]);\n",
)
replace_once(custom, "return `${selectedValues.length} alunos selecionados`;", "return `${selectedValues.length} itens selecionados`;")
replace_once(
    custom,
    "<div className={`relative flex flex-col gap-2 ${className}`} ref={rootRef}>",
    "<div className={`relative flex flex-col gap-2 ${className}`} ref={rootRef} style={{ minWidth: `min(${menuMinWidth}px, calc(100vw - 48px))` }}>",
)
replace_once(
    custom,
    "<div className=\"absolute left-0 right-0 top-full z-40 mt-2 max-h-60 overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-900\">",
    "<div className=\"absolute left-0 top-full z-40 mt-2 max-h-60 overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-900\" style={{ minWidth: `min(${menuMinWidth}px, calc(100vw - 48px))` }}>",
)

print('Patch applied')
